services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: falbackend_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/faldb
      - SPRING_DATASOURCE_USERNAME=sergen
      - SPRING_DATASOURCE_PASSWORD=1234
    volumes:
      - ./uploads:/app/uploads
    networks:
      - fal_network

  postgres:
    image: postgres:15
    container_name: faldb_container
    environment:
      POSTGRES_DB: faldb
      POSTGRES_USER: sergen
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fal_network

networks:
  fal_network:

volumes:
  postgres_data:
