
services:
  postgres:
    image: postgres:15
    container_name: faldb_container
    environment:
      POSTGRES_DB: faldb
      POSTGRES_USER: sergen
      POSTGRES_PASSWORD: 1234
      TZ: Europe/Istanbul
      PGTZ: Europe/Istanbul
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fal_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sergen -d faldb"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: falbackend_container
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./uploads:${APP_UPLOAD_DIR:-/app/uploads}
    networks:
      - fal_network
    restart: always

networks:
  fal_network:
    driver: bridge

volumes:
  postgres_data:
